name: CI

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/*.yml

env:
  DENO_TAG: v1.10.2

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu

    steps:
      - name: Checkout Deno
        uses: actions/checkout@v2
        with:
          repository: denoland/deno
          ref: ${{ env.DENO_TAG }}
          submodules: recursive

      - name: Toolchain Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.rustup/toolchains
            ~/.rustup/update-hashes
            ~/.rustup/settings.toml
          key: ${{ runner.os }}-rustup-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.target }}
          toolchain: stable
          profile: minimal
          override: true

      - name: Build Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: -p deno --target ${{ matrix.target }} --release --locked

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: deno-${{ env.DENO_TAG }}-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/deno
